/**
 * Decodes HTML entities commonly generated by the backend sanitization middleware
 * back into standard readable text characters.
 */
export function unescapeHtml(str: string): string {
  if (typeof str !== "string") return str;
  return str
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#x27;/g, "'")
    .replace(/&#x2F;/g, "/")
    .replace(/&apos;/g, "'");
}
